version: 2
jobs:
  build:
    working_directory: ~/ghc
    docker:
    - image: haskell:8
    resource_class: xlarge
    steps:
    - run:
        name: git
        command: |
          apt-get update
          apt-get install -y git openssh-client make automake autoconf gcc perl python3
    - checkout
    - run:
        name: submodules
        command: |
          # Use github.com/ghc for those submodule repositories we couldn't connect to.
          git config remote.origin.url git://github.com/ghc/ghc.git
          git config --global url."git://github.com/ghc/packages-".insteadOf git://github.com/ghc/packages/
          git submodule init # Don't be quiet, we want to show these urls.
          git submodule --quiet update --recursive # Now we can be quiet again.
    - run:
        name: build
        command: |
          echo 'BUILD_SPHINX_HTML  = NO' >> mk/validate.mk
          echo 'BUILD_SPHINX_PDF   = NO' >> mk/validate.mk
          THREADS=8 SKIP_PERF_TESTS=YES VERBOSE=2 ./validate --fast --quiet
