# For more information, see: http://docs.haskellstack.org/en/stable/yaml_configuration.html

# Specifies the GHC version and set of packages available (e.g., lts-3.5, nightly-2015-09-21, ghc-7.10.2)
resolver: lts-13.21

extra-deps:
# We need a newer happy (see #16825)
- git: https://github.com/simonmar/happy.git
  commit: 66982277ac7aed23edbb36c5f7aa5a86e5bdf778

# Local packages, usually specified by relative directory name
packages:
- '.'
- '../libraries/Cabal/Cabal'

nix:
   enable: false
   packages:
   - autoconf
   - automake
   - gcc
   - git
   - ncurses
   - perl
